name: Compile and Publish Apollo SDK NuGet Packages

on:
  pull_request: # whenever we open add commits to a pr targeting the main branch
    branches:
      - main
  push:
    branches:
      - main

jobs:
  compile:
    name: Compile Apollo SDK NuGet Packages
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      
      - name: compile libraries
        run: dotnet build ./apollo-sdk --configuration Release

      - name: testing libraries
        run: dotnet test ./apollo-sdk --no-restore --no-build --configuration Release

      - name: package libraries
        run: dotnet pack ./apollo-sdk --no-restore --no-build --configuration Release --output ./apollo-sdk/pkg

      - name: upload packages
        uses: actions/upload-artifact@v4
        with:
          name: apollo-sdk-nuget-packages
          path: ./apollo-sdk/pkg

  publish: # only run if we're committing to main
    name: Publish Apollo SDK NuGet Packages
    # if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    needs: compile
    runs-on: ubuntu-latest
    environment: production
    permissions:
      packages: write

    steps:
      - name: echo vars
        run: |
          echo ${{ github.ref }}
          echo ${{ github.ref_name }}
          echo ${{ github.event_name }}
      # - name: upload packages
      #   uses: actions/download-artifact@v4
      #   with:
      #     name: apollo-sdk-nuget-packages
      #     path: ./apollo-sdk/pkg

      # - name: publish libraries
      #   run: dotnet nuget push ./apollo-sdk/pkg/**/*.nupkg -s ${{ vars.NUGET_SOURCE }} -k ${{ secrets.GITHUB_TOKEN }} --skip-duplicate