name: Compile and Publish Apollo SDK NuGet Packages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  compile:
    name: Compile Apollo SDK NuGet Packages
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      
      # - name: configure nuget
      #   run: dotnet nuget add source --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }}
      
      - name: compile libraries
        run: dotnet build ./apollo-sdk --configuration Release

      - name: testing libraries
        run: dotnet test ./apollo-sdk --no-restore --no-build --configuration Release

      - name: package libraries
        run: dotnet pack ./apollo-sdk --no-restore --no-build --configuration Release --output ./apollo-sdk/pkg

      - name: publish libraries
        run: dotnet nuget push ./apollo-sdk/pkg/**/*.nupkg -s https://nuget.pkg.github.com/derrysmith/index.json -k ${{ secrets.GITHUB_TOKEN }} --skip-duplicate