name: CI/CD Pipeline for Shared .NET Core Libraries

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/shared-dotnet.pipeline.yml'
      - 'shared/dotnet/**'
  pull_request:
    branches: [ main ]
    paths:
      - '.github/workflows/shared-dotnet.pipeline.yml'
      - 'shared/dotnet/**'

jobs:
  build-test-pack:
    name: Build/Test/Pack .NET Core Libraries
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      # with:
      #   fetch-depth: 0
    
    - name: Configure .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'
    
    - name: Restore
      run: dotnet restore
      working-directory: ./shared/dotnet
    
    - name: Compile
      run: dotnet build --configuration Release --no-restore
      working-directory: ./shared/dotnet
    
    - name: Testing
      run: dotnet test --no-restore
      working-directory: ./shared/dotnet

    - name: Package (pre-release)
      if: github.event.pull_request.merged == false
      run: dotnet pack --configuration Release --no-restore --no-build -o pkg --version-suffix "ci-$(printf "%05d" ${{ github.event.pull_request.number }}).$(printf "%03d" ${{ github.run_number }})"
      working-directory: ./shared/dotnet

    - name: Package
      if: github.event.pull_request.merged == true
      run: dotnet pack --configuration Release --no-restore --no-build -o pkg
      working-directory: ./shared/dotnet

    - name: Publish
      run: dotnet nuget push "pkg/**/*.nupkg" -s "${{ vars.GH_PACKAGES_SOURCE }}" -k "${{ secrets.GH_PACKAGES_PAT }}" --skip-duplicate
      working-directory: ./shared/dotnet
        
        
        
        
        