name: CI/CD Pipeline for Shared .NET Core Libraries

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-pack:
    name: Build/Test/Pack .NET Core Libraries
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    
    - name: Configure .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'
    
    - name: Build/Test/Pack
      run: |
        dotnet restore ./shared/dotnet
        dotnet build ./shared/dotnet -c Release --no-restore
        dotnet test ./shared/dotnet --no-restore
        dotnet pack ./shared/dotnet -c Release --no-restore --no-build -o ./shared/dotnet/pkg --version-suffix "ci"
        dotnet nuget push "shared/dotnet/pkg/**/*.nupkg" -s "https://nuget.pkg.github.com/derrysmith/index.json" -k "${{ secrets.GH_PACKAGES_PAT }}" --skip-duplicate